stages:
  - test
  - deploy

test:
  stage: test
  script:
    - mkdir /tmp/gitlab_runner
    - cd /tmp/gitlab_runner
    - git clone git@github.com:kkr16/homeassistant-config.git
    - rm -rf /tmp/gitlab_runner

deploy:
  stage: deploy
  script:
    - cd /opt/homebase/homeassistant-config
    - git pull
    - sudo chown -R $USER:$USER /opt/homebase/homeassistant-config
    - git secret reveal -f
    - sudo docker-compose restart homeassistant